on: [push, pull_request]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go vet ./...
    - run: go test -v  -coverprofile=covprofile ./...
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: covprofile
